/*
 * This code is generated by rpcgen
 * and modified by Zarif Karim.
 */

#include "box_2.h"
#include <math.h>

int const SURFACE = 0;
int const VOLUME = 1;

 /* some worker procedures */
float calculate(int process, float l, float w, float h)
{
	float result;

	/* converting to nearest multiple of 3 */
	l = ceilf(l / 3) * 3;
	w = ceilf(w / 3) * 3;
	h = ceilf(h / 3) * 3;

	if (process == SURFACE)
	{
		result = 2 * (l * w + l * h + w * h);
	}
	else
	{
		result = l * w * h;
	}

	return result;
}

float postage(float v, float m)
{
	float result;

	if (v < m * 9)
	{
		result = v * 3;
	}
	else
	{
		result = m * 9 * 2;
	}
	
	return result;
}

box_results *
box_calc_2_svc(dimensions *argp, struct svc_req *rqstp)
{
	static box_results  result;

	result.volume = calculate(VOLUME, argp->length, argp->width, argp->height);
	result.surface = calculate(SURFACE, argp->length, argp->width, argp->height);

	return &result;
}

float *
mail_calc_2_svc(mail_dims *argp, struct svc_req *rqstp)
{
	static float  result;

	result = postage(argp->volume, argp->mass);

	return &result;
}
