/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "box.h"

 /* print out the box details */
void print_box(float l, float w, float h, float sa, float v)
{
	printf("A box of dimensions %f x %f x %f\n", l, w, h);
	printf("Has a surface area of %f\n", sa);
	printf("and a volume of %f\n", v);
	return;
}

void
rpc_box_1(char* host, float l, float w, float h)
{
	CLIENT* clnt;
	box_results* result_1;
	dimensions  box_calc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create(host, RPC_BOX, BOXVERSION1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	box_calc_1_arg.length = l;
	box_calc_1_arg.width = w;
	box_calc_1_arg.height = h;
#endif	/* DEBUG */

	result_1 = box_calc_1(&box_calc_1_arg, clnt);
	if (result_1 == (box_results*)NULL) {
		clnt_perror(clnt, "call failed");
	}

	/* print out the results */
	print_box(l, w, h, result_1->surface, result_1->volume);

#ifndef	DEBUG
	clnt_destroy(clnt);
#endif	 /* DEBUG */
}


int
main(int argc, char* argv[])
{
	char* host;
	float l, w, h;

	if (argc != 5)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}

	host = argv[1];

	if ((l = atof(argv[2])) <= 0 && *argv[2] != '0')
	{
		fprintf(stderr, "invalid value: %s\n", argv[2]);
		exit(1);
	}

	if ((w = atof(argv[3])) <= 0 && *argv[3] != '0')
	{
		fprintf(stderr, "invalid value: %s\n", argv[3]);
		exit(1);
	}

	if ((h = atof(argv[4])) <= 0 && *argv[3] != '0')
	{
		fprintf(stderr, "invalid value: %s\n", argv[3]);
		exit(1);
	}
	rpc_box_1(host, l, w, h);

	exit(0);
}
