/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BOX_H_RPCGEN
#define _BOX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dimensions {
	float length;
	float width;
	float height;
};
typedef struct dimensions dimensions;

struct box_results {
	float volume;
	float surface;
};
typedef struct box_results box_results;

#define RPC_BOX 0x40049453
#define BOXVERSION1 1

#if defined(__STDC__) || defined(__cplusplus)
#define BOX_CALC 1
extern  box_results * box_calc_1(dimensions *, CLIENT *);
extern  box_results * box_calc_1_svc(dimensions *, struct svc_req *);
extern int rpc_box_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define BOX_CALC 1
extern  box_results * box_calc_1();
extern  box_results * box_calc_1_svc();
extern int rpc_box_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dimensions (XDR *, dimensions*);
extern  bool_t xdr_box_results (XDR *, box_results*);

#else /* K&R C */
extern bool_t xdr_dimensions ();
extern bool_t xdr_box_results ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BOX_H_RPCGEN */
